// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func messageStyles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n        .message {\n            margin-bottom: 1rem;\n            padding: 1rem;\n            border-radius: 0.5rem;\n            background-color: #f8f9fa;\n        }\n\n        .message.thinking {\n            background-color: #e9ecef;\n        }\n\n        .message.error {\n            background-color: #ffe6e6;\n        }\n\n        .message.success {\n            background-color: #e6ffe6;\n        }\n\n        .message-header {\n            display: flex;\n            justify-content: space-between;\n            margin-bottom: 0.5rem;\n            font-size: 0.875rem;\n            color: #6c757d;\n        }\n\n        .message-content {\n            margin-bottom: 0.5rem;\n            line-height: 1.5;\n        }\n\n        .message-output {\n            font-family: monospace;\n            white-space: pre-wrap;\n            background-color: #f8f9fa;\n            padding: 0.5rem;\n            border-radius: 0.25rem;\n            font-size: 0.875rem;\n        }\n\n        .loading {\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            height: 100px;\n            font-style: italic;\n        }\n\n        #message-container::-webkit-scrollbar {\n            width: 8px;\n        }\n\n        #message-container::-webkit-scrollbar-track {\n            background: #f1f1f1;\n            border-radius: 4px;\n        }\n\n        #message-container::-webkit-scrollbar-thumb {\n            background: #888;\n            border-radius: 4px;\n        }\n\n        #message-container::-webkit-scrollbar-thumb:hover {\n            background: #555;\n        }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
